spring.application.name=siem

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/tfg_siem
spring.datasource.username=tfg_user
spring.datasource.password=tfg_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
