server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tfg_siem
    username: tfg_user
    password: tfg_pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false